Dark/light theme
Oleksii-Morozov/recipe-app pull request #1
Opened 2024-04-06 15:48 UTC by cupoftea4

https://trello.com/c/9yiTE4Bu/4-client-configure-dark-light-theme

2024-04-06 16:14 UTC, Oleksii-Morozov commented on utils/theme.ts
File theme.ts in directory styles exist, please move code to correct file

2024-04-06 16:14 UTC, Oleksii-Morozov commented on utils/theme.ts
> +
Why empty space?

2024-04-06 16:14 UTC, Oleksii-Morozov commented on utils/theme.ts
> +
Why empty space?

2024-04-06 16:17 UTC, Oleksii-Morozov requested changes
Plea

2024-04-06 16:17 UTC, Oleksii-Morozov commented on utils/theme.ts
> +
Why empty space?

2024-04-06 16:17 UTC, Oleksii-Morozov commented on utils/theme.ts
> +
Why empty space?

2024-04-06 16:17 UTC, Oleksii-Morozov commented on utils/theme.ts
Please move to styles/theme.ts

2024-04-06 18:57 UTC, cupoftea4 commented on utils/theme.ts
> +
Everything before space kind of differs for light and dark, and everything after - doesn't, but might in the future

2024-04-06 18:58 UTC, cupoftea4 commented on utils/theme.ts
i will move it in the next PR

2024-04-07 19:15 UTC, Oleksii-Morozov commented on utils/theme.ts
> +
Okay, but for future make it more understandable

2024-04-07 19:15 UTC, Oleksii-Morozov approved these changes

2024-04-07 19:15 UTC, merged